# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos"
    # Auth Error  due to key replacement: https://github.com/mitchellh/vagrant/issues/5186
    centos.ssh.insert_key = false
    centos.vbguest.auto_update = false
    centos.vm.network "forwarded_port", guest: 22, host: 1234
    centos.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "./env/vagrant_ansible_inventory_centos"
      ansible.playbook = "./env/centos.yml"
      ansible.sudo = true
#      ansible.verbose = 'v'
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "forwarded_port", guest: 22, host: 1235
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "./env/vagrant_ansible_inventory_ubuntu"
      ansible.playbook = "./env/ubuntu.yml"
      ansible.sudo = true
#      ansible.verbose = 'v'
    end
  end

  config.vm.synced_folder "./", "/host"
 
end
