# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.provider "virtualbox" do |vb|
        vb.gui = true
        # vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "forwarded_port", guest: 22, host: 1235
    ubuntu.vm.provision "shell", path: "./provision-ubuntu.sh"
  end
  config.vm.synced_folder "./", "/vagrant"
end
