# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.provider "hyperv" do |vb|
    	vb.memory = 2048
    end
    ubuntu.vm.box = "bento/ubuntu-16.04"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "public_network"
    #ubuntu.vm.network "forwarded_port", guest: 22, host: 1235
    ubuntu.vm.provision "shell", path: "./provision-ubuntu.sh"
  end
  config.vm.synced_folder ".", "/vagrant", type: "smb", disabled: true
end
